<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
?>
<?php
/**
 * @var \Amasty\Xsearch\Block\Search\Product $block
 * @var array $products
 */
$products = $block->getProducts();
?>

<?php if (count($products)) : ?>
    <div class="amsearch-products">
        <p class="amasty-xsearch-block-header">
            <?= __($block->getTitle())?>
        </p>
        <?php foreach ($products as $id => $product) : ?>
            <div class="amsearch-item product-item" data-click-url="<?= /* @escapeNotVerified */ $product['url'] ?>">
                <div class="amasty-xsearch-autocomplete-image">
                    <?= /* @escapeNotVerified */ $product['img'] ?>
                </div>
                <div class="amasty-xsearch-autocomplete-information">
                    <div class="information-container">
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $product['url'] ?>"
                                   title="<?= /* @escapeNotVerified */ $block->stripTags($product['name']); ?>"
                                >
                                    <?= /* @escapeNotVerified */ $product['name']; ?>
                                </a>
                            </strong>
                            <?php if ($block->isShowDescription($product)) :?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $product['description']?>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->getReviews()) : ?>
                                <?= $product['reviews']; ?>
                            <?php endif; ?>
                            <?= /* @escapeNotVerified */ $product['price'] ?>
                            <?php if ($block->getAddToCart()) : ?>
                                <div class="product actions product-item-actions" item-actions="1">
                                    <div class="actions-primary">
                                        <?php if ($product['is_salable']) : ?>
                                            <form id="<?= 'amasty-xsearch-product-' . $id;?>"
                                                  data-role="tocart-form"
                                                  action="<?= /* @escapeNotVerified */ $product['cart_post_params']['action']; ?>"
                                                  method="post" class="amasty-xsearch-form"
                                            >
                                                <input type="hidden" name="product"
                                                       value="<?= /* @escapeNotVerified */ $product['cart_post_params']['data']['product']; ?>">
                                                <?php if ($block->isRedirectToCartEnabled()) : ?>
                                                    <input type="hidden" name="return_url"
                                                           value="<?= /* @escapeNotVerified */ $product['cart_post_params']['data']['return_url']; ?>">
                                                <?php endif; ?>
                                                <input type="hidden"
                                                       name="<?= $block->getUlrEncodedParam(); ?>"
                                                       value="<?= $product['cart_post_params']['data'][$block->getUlrEncodedParam()]; ?>">
                                                <input name="form_key"
                                                       type="hidden"
                                                       value="<?= /* @escapeNotVerified */ $block->getFormKey() ?>"/>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else : ?>
                                            <?php if ($product['is_salable']) : ?>
                                                <div class="stock available">
                                                    <span><?=/* @escapeNotVerified */ __('In stock') ?></span>
                                                </div>
                                            <?php else : ?>
                                                <div class="stock unavailable">
                                                    <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>

                                    <div data-role="add-to-links" class="actions-secondary">
                                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?= $product['wishlist_post_params']; ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>

                                        <a href="#"
                                           class="action tocompare"
                                           title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?= $product['compare_post_params']; ?>'
                                           role="button">
                                            <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                        </a>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <?php if ($block->getNumResults() > $block->getLimit()) : ?>
            <div class="amasty-more-results">
                <a href="<?= /* @escapeNotVerified */ $block->getResultUrl() ?>"
                   title="<?= __('More products')?>">
                    <?= __('More products') ?>
                    <span> (<?= count($products) ?>)</span>
                </a>
            </div>
        <?php endif; ?>
    </div>

    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $('.amasty-xsearch-form').catalogAddToCart({});
        });
    </script>
<?php endif; ?>

