<div id="stalkerBox">
    <div class="stalkerButtonDiv">
        <span id="stalkerButtonSpan" title=""Get exclusive offers class="goToDisplay"></span>
    </div>
    <div id="newsletter-stalker">
        <div class="sub-container">
            <div class="content">
                <div class="stalker-register-form">
                    <span>Find out about new products and exclusive offers! <br/> We will not share your info with anyone.</span>
                    <form id="newsletter-registration-form-stalker" action="" method="post" id="newsletter-validate-detail-stalker">

                        <div class="form-fields-middle">
                            <div class="form-wrapper">
                                <input name="email" aria-label="Add your email to subscribe" id="cm_email2" class="cm_email validate-email required-entry field-left" type="text" placeholder="Email Address" />
                                <input id="mc-group" type="hidden" value="e76760f8e5" name="group">
                                <input type="submit" value="" class="button stalker-submit" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
