<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \Qxd\S3\Block\System\Config\Clearblock */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        jQuery('#syncWysiwyg_button').click(function () {
            var params = {};
            jQuery.ajax({
                showLoader: true,
                url: '<?php echo $block->getAjaxUrl() ?>',
                data: {},
                type: "GET",
                dataType: 'json'

            }).done(function (response) {

                console.log(response);
                if (response.status == '200')
                {
                    alert(response.data);
                }
                else{ alert('Error, please try again'); }


            }).error(function (err) {
                console.log('Error, please try again' ,  err);
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
